name: Windows-CRD

on: 
  workflow_dispatch:
  
jobs:
  build-iso:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2
    - name: Install winget
      run: |
           Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/pratyakshm/CleanWin/main/files/InstallWinGet.ps1'))
           winget install git -h
