name: Windows-CRD

on: 
  workflow_dispatch:
  
jobs:
  build-iso:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2
    - name: Compile image
      run: |
           Start-BitsTransfer "https://github.com/gus33000/UUPMediaCreator/releases/download/v0.3.0.6-fix/win-x64.zip"
           Expand-Archive "win-x64.zip"
           $currentdir = $(Get-Location).Path
           $dir = "$currentdir\win-x64\CLI"
           Set-Location $dir
           .\UUPDownload.exe -s Professional -v 10.0.22000.65 -r External -b Dev -c co_release -t amd64 -l en-US
